const boom = require('@hapi/boom')

/**
 * Validate a schema with Joi module
 * @param {Joi Object} schema - Schema generated by Joi
 * @param {string} property - property to acces in the request
 * @returns {function} - middleware function
 */
function validatorHandler (schema, property) {
  return (req, res, next) => {
    const data = req[property]
    const { error } = schema.validate(data, { abortEarly: false })
    if (error) {
      next(boom.badRequest(error))
    }
    next()
  }
}

module.exports = validatorHandler
