name: Testing CI
on: [push]
jobs:
  Unit-and-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install
        run: npm ci

      - name: Run unit and integration test
        run: |
          npm run test

  E2E-tests:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: tester123
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL
        run: npm run tsc && npm run migrations:run && npm run start
        env:
          DB_USER: postgres
          DB_PASSWORD: tester123
          DB_HOST: postgres
          DB_NAME: my_store
          DB_PORT: 5432
